version: '3'
services:
  php:
    image: php:7.4.18-apache-buster
    container_name: docker-php7.4
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - /home/guilherme/PhpProjects/Laravel-Projects/api-series:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: docker-mysql
    ports:
      - "3307:3306"
    volumes:
      - /path/on/host/mysql-data:/var/lib/mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: docker-api-series-db
